package exception;

public class RunTimeException {

	public static void main(String[] args) {

//	try {
//		//this is run time exception and handled by try and catch block
//		//but while compiling the compiler could not find the exception.
//		System.out.println(10/0);
//
//	}catch(Exception e) {
//		System.out.println(e.getMessage());
//	}

//	String s[]= {"aadi","noor"};
//	System.out.println(s[2]);

//		String s = "add";
		String s=null;
//		int length = s.length();
		System.out.println(s.length());
	}
}
